# Generated by Django 6.1.1 on 2026-09-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
    ]
