# Generated by Django 6.1.1 on 2026-09-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_usuario_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
